name: Calidad del Código y Tests

# Esto define cuándo se activa el robot
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga tu código en el servidor de GitHub
    - uses: actions/checkout@v3

    # 2. Instala Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    # 3. Instala las librerías de tu requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Revisa que el código esté bien escrito (Linting)
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # 5. Ejecuta las pruebas (aunque todavía no tengamos, preparamos el terreno)
    - name: Test with pytest
      run: |
        pytest
